post http://localhost:3001/api/users
content-type: application/json

{
    "username": "liiinder",
    "name": "Kristoffer Linder",
    "password": "qwerty"
}

###
post http://localhost:3001/api/users
content-type: application/json

{
    "username": "root",
    "name": "root",
    "password": "qwerty"
}

###
get http://localhost:3001/api/users

###
post http://localhost:3001/api/login
content-type: application/json

{
    "username": "liiinder",
    "password": "qwerty"
}

